// Each test case references its category by slug.
// testSteps and prerequisites are JSON-stringified arrays for SQLite compatibility.

export interface SeedTestCase {
  categorySlug: string;
  title: string;
  userStory: string;
  persona: string;
  testSteps: string; // JSON array
  prerequisites: string; // JSON array
  crmNotes: string | null;
  pageRef: string | null;
  displayOrder: number;
}

// ──────────────────────────────────────────────
// PRODUCTIVITY  (~31 test cases)
// ──────────────────────────────────────────────

const productivity: SeedTestCase[] = [
  {
    categorySlug: 'productivity',
    title: 'AI-Generated Sales Email Summary',
    userStory: 'As a seller, I want to see an AI-generated summary of a sales email so I can quickly understand key points without reading the full thread.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open Outlook and select a sales-related email thread with 3+ messages',
      'Open the Copilot for Sales side panel',
      'Verify an AI-generated summary appears automatically',
      'Confirm summary captures key entities (contacts, accounts, opportunities)',
      'Check that CRM record links are embedded in the summary',
    ]),
    prerequisites: JSON.stringify([
      'Copilot for Sales Outlook add-in installed',
      'User signed in to Salesforce CRM',
      'At least one email thread with CRM-related content',
    ]),
    crmNotes: 'Salesforce: Summary should detect and link Salesforce Contacts, Accounts, and Opportunities mentioned in the email.',
    pageRef: 'p6',
    displayOrder: 1,
  },
  {
    categorySlug: 'productivity',
    title: 'Generate Content Experience',
    userStory: 'As a seller, I want AI to help me draft email replies so I can communicate more effectively and save time.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open a sales email in Outlook',
      'Click "Draft with Copilot" or open the Copilot side panel',
      'Select a suggested reply option or enter a custom prompt',
      'Review the AI-generated draft content',
      'Edit the draft and insert it into the email reply',
      'Verify the draft references relevant CRM data',
    ]),
    prerequisites: JSON.stringify([
      'Copilot for Sales Outlook add-in installed',
      'Active Salesforce connection',
    ]),
    crmNotes: 'Draft content should pull context from linked Salesforce records.',
    pageRef: 'p7',
    displayOrder: 2,
  },
  {
    categorySlug: 'productivity',
    title: 'Record Search with Record Type Filter',
    userStory: 'As a seller, I want to search CRM records by type (Contact, Account, Opportunity) so I can quickly find the right record.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open the Copilot for Sales side panel in Outlook',
      'Click the search bar in the CRM records section',
      'Apply a record type filter (e.g., Contacts only)',
      'Enter a search term and verify filtered results appear',
      'Select a record and confirm it links correctly',
    ]),
    prerequisites: JSON.stringify([
      'Copilot for Sales side panel accessible',
      'Multiple CRM record types exist in Salesforce',
    ]),
    crmNotes: 'Salesforce: Filters should include standard objects — Contact, Account, Opportunity, Lead.',
    pageRef: 'p8-9',
    displayOrder: 3,
  },
  {
    categorySlug: 'productivity',
    title: 'Save Email to CRM',
    userStory: 'As a seller, I want to save emails (with attachments) to my CRM so that all client communications are tracked.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open a sales email with at least one attachment',
      'Open the Copilot for Sales side panel',
      'Click "Save to CRM" button',
      'Verify the email body is saved to the linked CRM record',
      'Verify attachments are included in the save',
      'Open Salesforce and confirm the activity and attachments appear on the record',
    ]),
    prerequisites: JSON.stringify([
      'Email linked to a Salesforce record',
      'Attachments present on the email',
    ]),
    crmNotes: 'Salesforce: Email saved as an Activity/Task. Attachments stored as ContentDocument linked to the parent record.',
    pageRef: 'p10',
    displayOrder: 4,
  },
  {
    categorySlug: 'productivity',
    title: 'Saving Emails with Additional Fields',
    userStory: 'As a seller, I want to categorize saved emails using custom CRM fields so my team can filter and report on communications.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open a sales email in Outlook',
      'Open the Copilot for Sales side panel',
      'Click "Save to CRM" and expand the additional fields section',
      'Set values for additional fields (e.g., email category, priority)',
      'Save and verify the fields are populated in Salesforce',
    ]),
    prerequisites: JSON.stringify([
      'Admin has configured additional save-to-CRM fields',
      'Email linked to a CRM record',
    ]),
    crmNotes: 'Salesforce: Admin must configure which additional fields appear via Admin Settings > Save to CRM Fields.',
    pageRef: 'p11',
    displayOrder: 5,
  },
  {
    categorySlug: 'productivity',
    title: 'Duplicate Contacts in CRM',
    userStory: 'As a seller, I want to be alerted when saving a contact that may already exist so I avoid creating duplicates.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open an email from a contact that already exists in Salesforce',
      'Open the Copilot for Sales side panel',
      'Attempt to create a new contact from the email',
      'Verify a duplicate detection warning appears',
      'Choose to view the existing record or proceed with creation',
    ]),
    prerequisites: JSON.stringify([
      'At least one contact in Salesforce matching the email sender',
    ]),
    crmNotes: 'Salesforce: Duplicate detection uses email address matching. Verify against Salesforce duplicate rules.',
    pageRef: 'p13',
    displayOrder: 6,
  },
  {
    categorySlug: 'productivity',
    title: 'Create Lead from Email',
    userStory: 'As a seller, I want to create a new CRM lead directly from an email so I can capture prospect information without switching apps.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open an email from an unknown sender (not in CRM)',
      'Open the Copilot for Sales side panel',
      'Click "Create Lead" option',
      'Verify pre-populated fields from email (name, email, company)',
      'Fill in any additional required fields',
      'Save and confirm the lead appears in Salesforce',
    ]),
    prerequisites: JSON.stringify([
      'Email from sender not currently in Salesforce',
      'Lead object enabled in Salesforce',
    ]),
    crmNotes: 'Salesforce: Lead is created as a standard Lead object. Company name is parsed from email domain if available.',
    pageRef: 'p14',
    displayOrder: 7,
  },
  {
    categorySlug: 'productivity',
    title: 'View and Edit Lead',
    userStory: 'As a seller, I want to view and edit lead details from the side panel so I can update information without leaving Outlook.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open an email linked to an existing Salesforce Lead',
      'Open the Copilot for Sales side panel',
      'Locate the linked Lead record and click to expand',
      'Verify lead details display correctly (name, company, status)',
      'Edit a field (e.g., Lead Status) and save',
      'Confirm the change persists in Salesforce',
    ]),
    prerequisites: JSON.stringify([
      'Existing Lead in Salesforce linked to an email',
    ]),
    crmNotes: 'Salesforce: Editable fields depend on the user\'s Salesforce profile permissions and field-level security.',
    pageRef: 'p15',
    displayOrder: 8,
  },
  {
    categorySlug: 'productivity',
    title: 'Latest Activities in Summary',
    userStory: 'As a seller, I want to see the latest CRM activities in the email summary so I have full context on recent interactions.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open an email linked to a Salesforce record with recent activities',
      'Open the Copilot for Sales side panel',
      'Scroll to the "Latest Activities" section in the summary',
      'Verify recent activities (calls, emails, meetings) are listed',
      'Confirm activity dates and descriptions are accurate',
    ]),
    prerequisites: JSON.stringify([
      'CRM record with at least 3 recent activities in Salesforce',
    ]),
    crmNotes: 'Salesforce: Activities pulled from the Activity Timeline on the linked record.',
    pageRef: 'p16',
    displayOrder: 9,
  },
  {
    categorySlug: 'productivity',
    title: 'Global View',
    userStory: 'As a seller, I want a global view of all my CRM-connected emails so I can see the overall status of my customer interactions.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open Outlook and access the Copilot for Sales global view',
      'Verify the view shows all CRM-connected communications',
      'Filter by record type or status',
      'Click on an item to navigate to the related email/record',
      'Confirm data refreshes when new emails arrive',
    ]),
    prerequisites: JSON.stringify([
      'Multiple emails saved to CRM across different records',
    ]),
    crmNotes: null,
    pageRef: 'p17',
    displayOrder: 10,
  },
  {
    categorySlug: 'productivity',
    title: 'CRM Suggested Updates - Opportunity',
    userStory: 'As a seller, I want Copilot to suggest CRM updates based on email content so I can keep my opportunity data current.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open an email that discusses deal progress, pricing, or timeline changes',
      'Open the Copilot for Sales side panel',
      'Look for "Suggested Updates" section for the linked Opportunity',
      'Review AI-suggested field updates (e.g., close date, amount, stage)',
      'Accept or dismiss each suggestion',
      'Verify accepted updates are applied in Salesforce',
    ]),
    prerequisites: JSON.stringify([
      'Email linked to a Salesforce Opportunity',
      'Email content references deal-related changes',
    ]),
    crmNotes: 'Salesforce: Suggestions target standard Opportunity fields — Amount, Close Date, Stage, Next Step.',
    pageRef: 'p18-19',
    displayOrder: 11,
  },
  {
    categorySlug: 'productivity',
    title: 'Objects Creation from Side Panel',
    userStory: 'As a seller, I want to create CRM objects (Account, Opportunity, etc.) directly from the side panel so I can capture new data in context.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open the Copilot for Sales side panel in Outlook',
      'Click the "+" or "Create" button',
      'Select the object type to create (Account, Opportunity, etc.)',
      'Fill in the required fields on the creation form',
      'Save and verify the object is created in Salesforce',
      'Confirm the new object is linked to the current email context',
    ]),
    prerequisites: JSON.stringify([
      'User has create permissions for the target object in Salesforce',
    ]),
    crmNotes: 'Salesforce: Object creation respects Salesforce validation rules and required field configurations.',
    pageRef: 'p20-21',
    displayOrder: 12,
  },
  {
    categorySlug: 'productivity',
    title: 'AI Powered Opportunity Suggestions',
    userStory: 'As a seller, I want AI to suggest relevant opportunities based on email context so I can link conversations to the right deals.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open a sales email discussing a potential deal',
      'Open the Copilot for Sales side panel',
      'Observe AI-suggested Opportunity matches',
      'Verify suggestions are ranked by relevance',
      'Select the correct opportunity to link',
      'Confirm the link is established in both Outlook and Salesforce',
    ]),
    prerequisites: JSON.stringify([
      'Multiple open Opportunities in Salesforce',
      'Email content that relates to one or more deals',
    ]),
    crmNotes: 'Salesforce: AI matches based on account name, contact associations, and deal keywords.',
    pageRef: 'p22',
    displayOrder: 13,
  },
  {
    categorySlug: 'productivity',
    title: 'Actionable Message Banners',
    userStory: 'As a seller, I want to see actionable banners on relevant emails so I can take CRM actions without opening the full side panel.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open a sales email that Copilot recognizes as CRM-relevant',
      'Verify an actionable banner appears at the top of the email',
      'Click a banner action (e.g., "Save to CRM", "View in Salesforce")',
      'Confirm the action completes successfully',
      'Verify the banner updates state after action (e.g., "Saved")',
    ]),
    prerequisites: JSON.stringify([
      'Copilot for Sales add-in installed and signed in',
    ]),
    crmNotes: null,
    pageRef: 'p23',
    displayOrder: 14,
  },
  {
    categorySlug: 'productivity',
    title: 'Key Sales Information',
    userStory: 'As a seller, I want to see key sales info (BANT, competitors, pricing) extracted from emails so I can prepare for conversations.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open a sales email containing deal-related information',
      'Open the Copilot for Sales side panel',
      'Locate the "Key Sales Info" section',
      'Verify extracted items: budget mentions, authority/decision-makers, needs, timeline',
      'Check that competitor mentions are highlighted',
      'Confirm pricing or financial figures are surfaced',
    ]),
    prerequisites: JSON.stringify([
      'Email with substantive sales discussion content',
    ]),
    crmNotes: null,
    pageRef: 'p24',
    displayOrder: 15,
  },
  {
    categorySlug: 'productivity',
    title: 'Enhanced Teams App - Reading & Composing',
    userStory: 'As a seller, I want to access Copilot for Sales within Teams messages so I can reference CRM data while communicating.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open Microsoft Teams and navigate to a chat or channel',
      'Open the Copilot for Sales app from the Teams app bar',
      'Verify CRM data is accessible in the reading pane',
      'Compose a new message and use the Copilot for Sales message extension',
      'Insert a CRM record reference into the message',
      'Verify the recipient can see the shared CRM card',
    ]),
    prerequisites: JSON.stringify([
      'Copilot for Sales Teams app installed',
      'Signed in to Salesforce',
    ]),
    crmNotes: null,
    pageRef: 'p25-26',
    displayOrder: 16,
  },
  {
    categorySlug: 'productivity',
    title: 'Enhanced Teams App Discovery - Search Message Extension',
    userStory: 'As a seller, I want to search CRM records directly from the Teams compose box so I can quickly share records in conversations.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open a Teams chat or channel',
      'Click the "..." (extensions) button in the compose box',
      'Search for and select the Copilot for Sales extension',
      'Enter a search term to find a CRM record',
      'Select a record from the search results',
      'Verify an adaptive card preview is inserted into the message',
    ]),
    prerequisites: JSON.stringify([
      'Copilot for Sales Teams message extension enabled',
    ]),
    crmNotes: null,
    pageRef: 'p27-28',
    displayOrder: 17,
  },
  {
    categorySlug: 'productivity',
    title: 'Global Entity Search',
    userStory: 'As a seller, I want to search across all CRM entity types in one search so I can find any record quickly.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open the Copilot for Sales side panel',
      'Use the global search bar at the top',
      'Enter a search term that could match multiple entity types',
      'Verify results include Contacts, Accounts, Opportunities, and Leads',
      'Click a result and confirm navigation to the correct record detail',
    ]),
    prerequisites: JSON.stringify([
      'CRM contains records across multiple entity types',
    ]),
    crmNotes: 'Salesforce: Search uses SOSL or REST API search across configured objects.',
    pageRef: 'p29',
    displayOrder: 18,
  },
  {
    categorySlug: 'productivity',
    title: 'Recent Communications',
    userStory: 'As a seller, I want to see recent communications for a CRM record so I have context on the latest interactions.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open the Copilot for Sales side panel for a linked record',
      'Navigate to the "Recent Communications" section',
      'Verify recent emails, meetings, and calls are listed chronologically',
      'Click on a communication item to view details',
      'Confirm timestamps and participants are accurate',
    ]),
    prerequisites: JSON.stringify([
      'CRM record with multiple recent communications tracked',
    ]),
    crmNotes: null,
    pageRef: 'p30',
    displayOrder: 19,
  },
  {
    categorySlug: 'productivity',
    title: 'Infobar Banners',
    userStory: 'As a seller, I want informational banners in Outlook to remind me of CRM-related actions on emails.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open various sales emails in Outlook',
      'Observe infobar banners appearing for CRM-connected emails',
      'Verify banners show relevant status (e.g., "Saved to CRM", "Not connected")',
      'Click on a banner to take action (save, connect, or open record)',
      'Confirm the banner state updates after the action',
    ]),
    prerequisites: JSON.stringify([
      'Copilot for Sales add-in enabled',
    ]),
    crmNotes: null,
    pageRef: 'p32',
    displayOrder: 20,
  },
  {
    categorySlug: 'productivity',
    title: 'Sales Agent - Account Summary & Reports',
    userStory: 'As a seller, I want Sales Agent to generate account summaries and quarterly reports so I can quickly get insights on my accounts.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open the Sales Agent chat interface',
      'Request an account summary for a specific account',
      'Verify the summary includes key metrics, contacts, and recent activity',
      'Request a quarterly revenue report',
      'Verify the report includes revenue comparison data',
      'Check that data matches Salesforce records',
    ]),
    prerequisites: JSON.stringify([
      'Sales Agent enabled by admin',
      'Salesforce connected with sufficient account data',
    ]),
    crmNotes: 'Salesforce: Agent pulls data from Account, Opportunity, and Activity objects.',
    pageRef: 'p33-36',
    displayOrder: 21,
  },
  {
    categorySlug: 'productivity',
    title: 'Prepare for Sales Meetings',
    userStory: 'As a seller, I want Copilot to help me prepare for upcoming sales meetings by surfacing relevant CRM data and talking points.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open an upcoming calendar event in Outlook that has external attendees',
      'Open the Copilot for Sales side panel',
      'Verify meeting preparation card appears',
      'Check that attendee CRM profiles are surfaced',
      'Verify related opportunities and recent activities are shown',
      'Review AI-suggested talking points',
    ]),
    prerequisites: JSON.stringify([
      'Calendar meeting with CRM-known external attendees',
      'At least one linked Opportunity for the account',
    ]),
    crmNotes: null,
    pageRef: 'p44-46',
    displayOrder: 22,
  },
  {
    categorySlug: 'productivity',
    title: 'Save, Use Suggestions & Custom Prompts',
    userStory: 'As a seller, I want to save useful prompts and reuse AI suggestions so I can streamline my workflow.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open Copilot for Sales and generate a suggestion',
      'Save a useful prompt for later reuse',
      'Navigate to saved prompts and verify it appears',
      'Use a saved prompt and verify it generates relevant content',
      'Create a custom prompt and verify it produces expected output',
    ]),
    prerequisites: JSON.stringify([
      'Copilot for Sales active with AI features enabled',
    ]),
    crmNotes: null,
    pageRef: 'p140',
    displayOrder: 23,
  },
  {
    categorySlug: 'productivity',
    title: 'Text Moderation in AI Content',
    userStory: 'As a seller, I want AI-generated content to be moderated for appropriateness so I can trust the suggestions.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open Copilot for Sales and request content generation',
      'Attempt to generate content with potentially inappropriate prompts',
      'Verify that content moderation blocks or flags inappropriate content',
      'Generate normal business content and verify it passes moderation',
      'Check that moderation does not over-filter legitimate sales language',
    ]),
    prerequisites: JSON.stringify([
      'Copilot for Sales with AI content generation enabled',
    ]),
    crmNotes: null,
    pageRef: 'p141',
    displayOrder: 24,
  },
  {
    categorySlug: 'productivity',
    title: 'Catch Up, Draft Emails & Take Actions',
    userStory: 'As a seller, I want a "catch up" experience that summarizes what I missed and lets me draft responses or take CRM actions.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open Copilot for Sales after a period of inactivity',
      'Verify the "Catch Up" view shows unread CRM-relevant emails',
      'Review AI summaries for each catch-up item',
      'Draft a quick response using the inline draft feature',
      'Take a CRM action (e.g., update opportunity stage) from the catch-up view',
    ]),
    prerequisites: JSON.stringify([
      'Multiple unread sales emails accumulated',
    ]),
    crmNotes: null,
    pageRef: 'p142',
    displayOrder: 25,
  },
  {
    categorySlug: 'productivity',
    title: 'Change Language of Key Info',
    userStory: 'As a seller, I want to change the display language of key sales information so I can work in my preferred language.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open the Copilot for Sales side panel',
      'Navigate to key sales information for an email',
      'Look for the language change option',
      'Switch to a different supported language',
      'Verify the key info content re-renders in the selected language',
    ]),
    prerequisites: JSON.stringify([
      'Multi-language support enabled',
    ]),
    crmNotes: null,
    pageRef: 'p143',
    displayOrder: 26,
  },
  {
    categorySlug: 'productivity',
    title: 'Draft Email Options',
    userStory: 'As a seller, I want multiple draft email options so I can choose the best tone and content for my reply.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open a sales email and click "Draft with Copilot"',
      'Verify multiple draft options are presented',
      'Review at least 2 different draft suggestions',
      'Select one draft and verify it inserts into the reply',
      'Confirm the selected draft includes relevant CRM context',
    ]),
    prerequisites: JSON.stringify([
      'Copilot for Sales with draft email feature enabled',
    ]),
    crmNotes: null,
    pageRef: 'p144',
    displayOrder: 27,
  },
  {
    categorySlug: 'productivity',
    title: 'Adjust Tone of AI Content',
    userStory: 'As a seller, I want to adjust the tone of AI-generated content (formal, casual, concise) so it matches the communication context.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Generate an AI draft email',
      'Select the "Adjust Tone" option',
      'Choose "Professional/Formal" and verify the tone shifts',
      'Choose "Friendly/Casual" and verify the tone shifts',
      'Choose "Concise" and verify the content is shortened',
    ]),
    prerequisites: JSON.stringify([
      'AI draft email feature available',
    ]),
    crmNotes: null,
    pageRef: 'p135',
    displayOrder: 28,
  },
  {
    categorySlug: 'productivity',
    title: 'Suggest a Meeting Time',
    userStory: 'As a seller, I want Copilot to suggest meeting times based on my calendar availability so I can quickly propose times to customers.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open a sales email where a meeting is being discussed',
      'Open Copilot for Sales and look for meeting time suggestions',
      'Verify suggested times align with your calendar availability',
      'Select a suggested time and insert it into a reply',
      'Confirm the suggested format is clear and professional',
    ]),
    prerequisites: JSON.stringify([
      'Outlook calendar with existing appointments',
      'Email discussing scheduling a meeting',
    ]),
    crmNotes: null,
    pageRef: 'p136',
    displayOrder: 29,
  },
  {
    categorySlug: 'productivity',
    title: 'Refine Enhancements',
    userStory: 'As a seller, I want to iteratively refine AI suggestions so I can fine-tune the output to my needs.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Generate an AI content suggestion',
      'Use the "Refine" option to request modifications',
      'Provide specific refinement instructions (e.g., "make it shorter", "add pricing")',
      'Verify the refined output incorporates the feedback',
      'Refine again and verify iterative improvement',
    ]),
    prerequisites: JSON.stringify([
      'AI content generation active',
    ]),
    crmNotes: null,
    pageRef: 'p138',
    displayOrder: 30,
  },
  {
    categorySlug: 'productivity',
    title: 'Explanations for Seller Prompts',
    userStory: 'As a seller, I want clear explanations of what each AI prompt does so I can choose the right one for my situation.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open the Copilot for Sales prompt menu',
      'Hover over or expand a prompt option',
      'Verify an explanation or tooltip describes what the prompt does',
      'Try multiple prompts and confirm descriptions match behavior',
      'Check that custom prompts also support descriptions',
    ]),
    prerequisites: JSON.stringify([
      'Copilot for Sales with prompt suggestions enabled',
    ]),
    crmNotes: null,
    pageRef: 'p139',
    displayOrder: 31,
  },
];

// ──────────────────────────────────────────────
// INTERACTIONS  (~7 test cases)
// ──────────────────────────────────────────────

const interactions: SeedTestCase[] = [
  {
    categorySlug: 'interactions',
    title: 'Pre-Meeting Preparation',
    userStory: 'As a seller, I want Copilot to surface relevant CRM data before a meeting so I am well-prepared.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open an upcoming Teams meeting with external attendees',
      'Open the Copilot for Sales panel before the meeting starts',
      'Verify attendee profiles with CRM data are displayed',
      'Check that related opportunities and account info are surfaced',
      'Review AI-generated talking points and conversation starters',
      'Verify recent communication history is shown for each attendee',
    ]),
    prerequisites: JSON.stringify([
      'Teams meeting scheduled with CRM-known external contacts',
      'Copilot for Sales enabled for Teams meetings',
    ]),
    crmNotes: 'Salesforce: Meeting attendee matching uses email address lookup against Salesforce Contacts.',
    pageRef: 'p50',
    displayOrder: 1,
  },
  {
    categorySlug: 'interactions',
    title: 'Meeting Preparation Summary',
    userStory: 'As a seller, I want an AI-generated meeting preparation summary so I can review all relevant context in one place.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open a scheduled Teams meeting from the calendar',
      'Access the Copilot for Sales meeting prep view',
      'Verify the summary includes: attendee roles, company info, deal status',
      'Check that action items from previous meetings are listed',
      'Verify the summary updates if meeting attendees change',
    ]),
    prerequisites: JSON.stringify([
      'Teams meeting with at least 2 external attendees',
      'Previous meeting notes or interactions exist for the account',
    ]),
    crmNotes: null,
    pageRef: 'p51',
    displayOrder: 2,
  },
  {
    categorySlug: 'interactions',
    title: 'Access CRM Data During Meeting',
    userStory: 'As a seller, I want to access CRM data in real-time during a Teams meeting so I can reference deal details live.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Join a Teams meeting with Copilot for Sales enabled',
      'Open the Copilot for Sales panel during the meeting',
      'Search for a CRM record while the meeting is active',
      'Verify record details (opportunities, contacts) load correctly',
      'Reference CRM data points during the conversation',
      'Confirm no performance degradation during the meeting',
    ]),
    prerequisites: JSON.stringify([
      'Active Teams meeting',
      'Copilot for Sales meeting integration enabled',
    ]),
    crmNotes: 'Salesforce: Real-time data access requires an active Salesforce API connection during the meeting.',
    pageRef: 'p52-54',
    displayOrder: 3,
  },
  {
    categorySlug: 'interactions',
    title: 'Post-Meeting Sales Summary',
    userStory: 'As a seller, I want an AI-generated post-meeting summary with action items so I can quickly follow up on commitments.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Complete a Teams meeting with recording/transcription enabled',
      'Wait for the meeting recap to generate',
      'Open the Copilot for Sales section of the meeting recap',
      'Verify the sales summary highlights key discussion points',
      'Check that action items are extracted with owners',
      'Verify mentioned CRM entities are linked correctly',
      'Confirm follow-up suggestions are actionable',
    ]),
    prerequisites: JSON.stringify([
      'Teams meeting with transcription enabled',
      'Meeting had substantive sales discussion',
      'Copilot for Sales meeting recap feature enabled',
    ]),
    crmNotes: 'Salesforce: Summary may suggest updating Opportunity fields based on meeting discussion.',
    pageRef: 'p55-56',
    displayOrder: 4,
  },
  {
    categorySlug: 'interactions',
    title: 'Save AI Meeting Notes to CRM',
    userStory: 'As a seller, I want to save AI-generated meeting notes directly to my CRM so the team has a record of the conversation.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'After a Teams meeting, open the meeting recap',
      'Review the AI-generated meeting notes',
      'Click "Save to CRM" on the meeting notes',
      'Select or confirm the CRM record to save notes to',
      'Verify notes appear in Salesforce on the linked record',
      'Confirm note content includes key points and action items',
    ]),
    prerequisites: JSON.stringify([
      'Completed Teams meeting with AI-generated notes',
      'CRM record to link the meeting notes to',
    ]),
    crmNotes: 'Salesforce: Meeting notes saved as a Note or Activity on the record. Admin configures the save behavior.',
    pageRef: 'p57-59',
    displayOrder: 5,
  },
  {
    categorySlug: 'interactions',
    title: 'Follow-Up Email from Meeting',
    userStory: 'As a seller, I want Copilot to draft a follow-up email after a meeting so I can quickly send a professional recap to attendees.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'After a Teams meeting, open the meeting recap',
      'Click "Draft Follow-Up Email"',
      'Verify the draft includes meeting summary points',
      'Check that action items and next steps are included',
      'Edit the draft as needed',
      'Send the email and verify it is tracked in CRM',
    ]),
    prerequisites: JSON.stringify([
      'Completed Teams meeting with transcription',
      'Copilot for Sales post-meeting features enabled',
    ]),
    crmNotes: null,
    pageRef: 'p61',
    displayOrder: 6,
  },
  {
    categorySlug: 'interactions',
    title: 'Copilot for Sales Automatically Added to Meetings',
    userStory: 'As a seller, I want Copilot for Sales to be automatically added to my meetings with external participants so I always get CRM insights.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Schedule a new Teams meeting with at least one external attendee',
      'Check that Copilot for Sales is automatically added as a meeting resource',
      'Join the meeting and verify the Copilot for Sales panel is accessible',
      'Verify automatic addition works for recurring meetings',
      'Test that internal-only meetings do NOT auto-add Copilot for Sales',
    ]),
    prerequisites: JSON.stringify([
      'Admin has enabled automatic meeting addition',
      'Copilot for Sales license assigned to the user',
    ]),
    crmNotes: null,
    pageRef: 'p62',
    displayOrder: 7,
  },
];

// ──────────────────────────────────────────────
// FLOW OF WORK  (~15 test cases)
// ──────────────────────────────────────────────

const flowOfWork: SeedTestCase[] = [
  {
    categorySlug: 'flow-of-work',
    title: 'AI-Suggested Contact Creation',
    userStory: 'As a seller, I want AI to suggest creating new contacts from email participants so I can keep my CRM up to date.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open an email with participants not in Salesforce',
      'Open the Copilot for Sales side panel',
      'Verify AI suggests creating new contacts for unknown participants',
      'Review pre-populated contact details from the email',
      'Accept the suggestion to create the contact',
      'Verify the contact appears in Salesforce',
    ]),
    prerequisites: JSON.stringify([
      'Email with participants not currently in Salesforce',
    ]),
    crmNotes: 'Salesforce: Contact is created under the matched or suggested Account.',
    pageRef: 'p64-65',
    displayOrder: 1,
  },
  {
    categorySlug: 'flow-of-work',
    title: 'Collaboration Spaces - Contextual Entry Points',
    userStory: 'As a seller, I want easy access to collaboration spaces from CRM context so I can quickly collaborate with my team.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open Copilot for Sales in Outlook or Teams',
      'Navigate to a CRM record (Account or Opportunity)',
      'Look for the "Collaborate" or collaboration space entry point',
      'Click to open or create a collaboration space',
      'Verify the space is pre-linked to the CRM record',
    ]),
    prerequisites: JSON.stringify([
      'Collaboration Spaces feature enabled by admin',
      'Teams connected',
    ]),
    crmNotes: null,
    pageRef: 'p66',
    displayOrder: 2,
  },
  {
    categorySlug: 'flow-of-work',
    title: 'Collaboration Spaces - Account Team',
    userStory: 'As a seller, I want to create an Account Team collaboration space so my team can collaborate on account strategy in Teams.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Navigate to a Salesforce Account in the Copilot for Sales panel',
      'Click "Create Collaboration Space" > "Account Team"',
      'Verify a Teams channel is created linked to the account',
      'Check that relevant CRM data is pinned in the channel',
      'Invite team members and verify they can access CRM context',
      'Verify CRM record changes are reflected in the space',
    ]),
    prerequisites: JSON.stringify([
      'Collaboration Spaces enabled',
      'Microsoft Teams available',
      'Salesforce Account with team members',
    ]),
    crmNotes: 'Salesforce: Account Team members may be auto-suggested from the Salesforce Account Team.',
    pageRef: 'p67-71',
    displayOrder: 3,
  },
  {
    categorySlug: 'flow-of-work',
    title: 'Collaboration Spaces - Deal Room',
    userStory: 'As a seller, I want to create a Deal Room collaboration space for an opportunity so the deal team can coordinate in one place.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Navigate to a Salesforce Opportunity in the side panel',
      'Click "Create Collaboration Space" > "Deal Room"',
      'Verify a Teams channel is created linked to the Opportunity',
      'Check that deal details (stage, amount, close date) are shown',
      'Share deal updates and verify they sync with CRM',
      'Verify the deal room is accessible from both Teams and Outlook',
    ]),
    prerequisites: JSON.stringify([
      'Collaboration Spaces enabled',
      'Open Salesforce Opportunity',
    ]),
    crmNotes: 'Salesforce: Deal Room pulls Opportunity fields and related Contacts.',
    pageRef: 'p72-73',
    displayOrder: 4,
  },
  {
    categorySlug: 'flow-of-work',
    title: 'Share CRM Record in Teams Conversation',
    userStory: 'As a seller, I want to share a CRM record in a Teams conversation so my colleagues can see the context.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open a Teams chat or channel conversation',
      'Use the Copilot for Sales message extension or "/" command',
      'Search for and select a CRM record to share',
      'Verify an adaptive card with record details is sent',
      'Confirm the recipient can view the record details on the card',
      'Click through to open the full record in CRM',
    ]),
    prerequisites: JSON.stringify([
      'Copilot for Sales Teams app installed',
      'CRM record to share',
    ]),
    crmNotes: null,
    pageRef: 'p74-75',
    displayOrder: 5,
  },
  {
    categorySlug: 'flow-of-work',
    title: 'People.ai Integration (Salesforce)',
    userStory: 'As a seller using People.ai, I want integrated activity capture so my CRM has complete engagement data.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Verify People.ai integration is configured alongside Copilot for Sales',
      'Send emails and attend meetings tracked by both systems',
      'Open the Copilot for Sales side panel and check activity data',
      'Verify People.ai enrichment data appears in CRM context',
      'Confirm no duplicate activity records are created',
    ]),
    prerequisites: JSON.stringify([
      'People.ai integration enabled (Salesforce only)',
      'Copilot for Sales connected to the same Salesforce org',
    ]),
    crmNotes: 'Salesforce only: People.ai integration is exclusive to Salesforce CRM environments.',
    pageRef: 'p76',
    displayOrder: 6,
  },
  {
    categorySlug: 'flow-of-work',
    title: 'Duplicate Contacts Detection in Flow',
    userStory: 'As a seller, I want Copilot to detect potential duplicate contacts when creating from email so I maintain data quality.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open an email from a contact with a similar name to an existing CRM contact',
      'Trigger contact creation from the side panel',
      'Verify duplicate detection identifies the potential match',
      'Review the comparison of the new vs existing contact',
      'Choose to merge, skip, or create anyway',
      'Confirm the chosen action is reflected in Salesforce',
    ]),
    prerequisites: JSON.stringify([
      'Existing contacts in Salesforce with similar names/emails',
    ]),
    crmNotes: 'Salesforce: Leverages Salesforce duplicate rules and matching rules.',
    pageRef: 'p77',
    displayOrder: 7,
  },
  {
    categorySlug: 'flow-of-work',
    title: 'Sign-in for Third-Party Plugins',
    userStory: 'As a seller, I want to sign into third-party plugins from Copilot for Sales so I can use extended integrations.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open Copilot for Sales and navigate to plugin settings',
      'Select a third-party plugin (e.g., DocuSign)',
      'Initiate the sign-in flow for the plugin',
      'Complete authentication using plugin credentials',
      'Verify the plugin shows as connected',
      'Access plugin features from within Copilot for Sales',
    ]),
    prerequisites: JSON.stringify([
      'Third-party plugin configured by admin',
      'User has credentials for the third-party service',
    ]),
    crmNotes: null,
    pageRef: 'p78',
    displayOrder: 8,
  },
  {
    categorySlug: 'flow-of-work',
    title: 'DocuSign Integration',
    userStory: 'As a seller, I want to send documents for signature via DocuSign from within Copilot for Sales so I can close deals faster.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open Copilot for Sales in context of an Opportunity',
      'Access the DocuSign integration option',
      'Select a document to send for signature',
      'Add recipients from CRM contacts',
      'Send the document for signing',
      'Verify the signing status is trackable from the side panel',
      'Confirm the signed document links back to the CRM record',
    ]),
    prerequisites: JSON.stringify([
      'DocuSign plugin installed and configured',
      'User signed into DocuSign',
      'Document ready for signature',
    ]),
    crmNotes: null,
    pageRef: 'p79',
    displayOrder: 9,
  },
  {
    categorySlug: 'flow-of-work',
    title: 'Actionable Cards Across Environments',
    userStory: 'As a seller, I want adaptive cards in Teams, Outlook, and other surfaces to show CRM actions so I can act from any context.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Receive a Copilot for Sales adaptive card in Teams',
      'Verify the card shows relevant CRM data and action buttons',
      'Click an action button (e.g., "Update Stage", "View Record")',
      'Verify the same card format works in Outlook notifications',
      'Confirm actions taken on cards are reflected in Salesforce',
    ]),
    prerequisites: JSON.stringify([
      'Copilot for Sales adaptive cards enabled',
      'CRM data available for the context',
    ]),
    crmNotes: null,
    pageRef: 'p80',
    displayOrder: 10,
  },
  {
    categorySlug: 'flow-of-work',
    title: 'AI Generated Planner Tasks',
    userStory: 'As a seller, I want Copilot to automatically create Planner tasks from meeting action items so nothing falls through the cracks.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Complete a Teams meeting with clear action items discussed',
      'Open the meeting recap and review action items',
      'Verify "Create Planner Task" option is available for each action item',
      'Create a Planner task from an action item',
      'Verify the task appears in Microsoft Planner with correct details',
      'Check that the task is linked back to the meeting and CRM context',
    ]),
    prerequisites: JSON.stringify([
      'Microsoft Planner available',
      'Teams meeting with transcription and action item extraction',
    ]),
    crmNotes: null,
    pageRef: 'p81',
    displayOrder: 11,
  },
  {
    categorySlug: 'flow-of-work',
    title: 'Extension Points via Copilot Studio',
    userStory: 'As an admin, I want to extend Copilot for Sales with custom actions through Copilot Studio so we can add organization-specific workflows.',
    persona: 'Admin',
    testSteps: JSON.stringify([
      'Open Copilot Studio and navigate to Copilot for Sales extensions',
      'Create a new custom action or plugin',
      'Configure the action with CRM data triggers or conditions',
      'Publish the extension to the Copilot for Sales experience',
      'Test the custom action from the seller perspective',
      'Verify the action executes correctly and updates CRM as expected',
    ]),
    prerequisites: JSON.stringify([
      'Copilot Studio access with appropriate licenses',
      'Copilot for Sales deployed',
    ]),
    crmNotes: 'Salesforce: Custom actions can interact with Salesforce objects via the connector.',
    pageRef: 'p82-84',
    displayOrder: 12,
  },
  {
    categorySlug: 'flow-of-work',
    title: 'Sharing Records in Emails',
    userStory: 'As a seller, I want to embed CRM record references in emails using "/" commands so recipients can see deal context.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Compose a new email in Outlook',
      'Type "/" to invoke the Copilot for Sales command menu',
      'Search for and select a CRM record to embed',
      'Verify the record is inserted as a rich card in the email body',
      'Send the email and verify the recipient sees the record summary',
    ]),
    prerequisites: JSON.stringify([
      'Sharing records in emails feature enabled by admin',
      'Copilot for Sales Outlook add-in active',
    ]),
    crmNotes: null,
    pageRef: 'p85',
    displayOrder: 13,
  },
  {
    categorySlug: 'flow-of-work',
    title: 'Copilot for Sales in Outlook Mobile',
    userStory: 'As a seller, I want to use Copilot for Sales on Outlook mobile so I can access CRM data on the go.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Open Outlook on a mobile device (iOS or Android)',
      'Open a sales email and access the Copilot for Sales add-in',
      'Verify CRM data loads correctly on the mobile interface',
      'Test core actions: view record, save email, view summary',
      'Confirm the mobile experience is responsive and usable',
    ]),
    prerequisites: JSON.stringify([
      'Outlook mobile app installed',
      'Copilot for Sales mobile support enabled',
    ]),
    crmNotes: null,
    pageRef: 'p86',
    displayOrder: 14,
  },
  {
    categorySlug: 'flow-of-work',
    title: 'Improved Teams Meeting Recap Notifications',
    userStory: 'As a seller, I want improved meeting recap notifications so I am promptly informed when CRM-relevant summaries are ready.',
    persona: 'Seller',
    testSteps: JSON.stringify([
      'Complete a Teams meeting with Copilot for Sales active',
      'Wait for the meeting recap to be generated',
      'Verify a notification is received in Teams',
      'Check that the notification includes a CRM-specific summary preview',
      'Click the notification and verify it opens the full recap',
      'Confirm notification timing is within a reasonable window post-meeting',
    ]),
    prerequisites: JSON.stringify([
      'Teams meeting with transcription completed',
      'Copilot for Sales meeting integration enabled',
    ]),
    crmNotes: null,
    pageRef: 'p87',
    displayOrder: 15,
  },
];

// ──────────────────────────────────────────────
// ADMINISTRATION  (~19 test cases)
// ──────────────────────────────────────────────

const administration: SeedTestCase[] = [
  {
    categorySlug: 'administration',
    title: 'Admin Settings Landing Page',
    userStory: 'As an admin, I want a centralized settings landing page so I can manage all Copilot for Sales configurations in one place.',
    persona: 'Admin',
    testSteps: JSON.stringify([
      'Sign in as a tenant or environment admin',
      'Navigate to the Copilot for Sales admin settings',
      'Verify the landing page shows all configuration sections',
      'Confirm navigation links work to each settings area',
      'Verify your admin role is displayed correctly',
    ]),
    prerequisites: JSON.stringify([
      'Admin role assigned (Tenant Admin or Environment Admin)',
      'Copilot for Sales deployed in the tenant',
    ]),
    crmNotes: null,
    pageRef: 'p95',
    displayOrder: 1,
  },
  {
    categorySlug: 'administration',
    title: 'Copilot Settings at Tenant Level',
    userStory: 'As a tenant admin, I want to configure Copilot for Sales settings at the tenant level so they apply across all environments.',
    persona: 'Tenant Admin',
    testSteps: JSON.stringify([
      'Navigate to Admin Settings > Tenant Level Settings',
      'Configure a tenant-wide setting (e.g., enable/disable a feature)',
      'Save the configuration',
      'Verify the setting applies across multiple environments',
      'Check that environment admins see the tenant-level setting as inherited',
    ]),
    prerequisites: JSON.stringify([
      'Tenant Admin role',
      'Multiple environments configured',
    ]),
    crmNotes: null,
    pageRef: 'p96',
    displayOrder: 2,
  },
  {
    categorySlug: 'administration',
    title: 'Exposure of Copilot Capabilities',
    userStory: 'As an admin, I want to progressively roll out Copilot capabilities to specific user groups so I can control adoption.',
    persona: 'Admin',
    testSteps: JSON.stringify([
      'Navigate to Admin Settings > Copilot Capabilities',
      'Select a feature to expose (e.g., AI email summaries)',
      'Configure the feature to be available for a specific user group',
      'Save and verify the feature is visible only to the target group',
      'Add another group and verify they also gain access',
      'Verify users not in any group cannot see the feature',
    ]),
    prerequisites: JSON.stringify([
      'Admin role with feature management permissions',
      'User groups/security groups configured in Microsoft 365',
    ]),
    crmNotes: null,
    pageRef: 'p97',
    displayOrder: 3,
  },
  {
    categorySlug: 'administration',
    title: 'Save to CRM Fields Configuration',
    userStory: 'As an admin, I want to configure which additional fields appear when sellers save emails to CRM so data is properly categorized.',
    persona: 'Admin',
    testSteps: JSON.stringify([
      'Navigate to Admin Settings > Save to CRM Fields',
      'Add a new field (e.g., Email Category) to the save form',
      'Configure field options and whether it is required',
      'Save the configuration',
      'Sign in as a seller and verify the new field appears when saving an email',
      'Verify saved data includes the additional field in Salesforce',
    ]),
    prerequisites: JSON.stringify([
      'Admin access to Copilot for Sales settings',
      'Target Salesforce fields exist and are accessible',
    ]),
    crmNotes: 'Salesforce: Fields must be mapped to existing Salesforce custom or standard fields on the Activity/Task object.',
    pageRef: 'p98',
    displayOrder: 4,
  },
  {
    categorySlug: 'administration',
    title: 'Admin Settings Forms - Customize CRM Display',
    userStory: 'As an admin, I want to customize which CRM fields and objects are displayed in the side panel so sellers see relevant information.',
    persona: 'Admin',
    testSteps: JSON.stringify([
      'Navigate to Admin Settings > Forms',
      'Select a CRM object (e.g., Opportunity)',
      'Add, remove, or reorder the fields displayed in the side panel',
      'Add a new CRM object to the side panel display',
      'Save and verify changes appear for sellers in the side panel',
      'Verify field display order matches the configuration',
    ]),
    prerequisites: JSON.stringify([
      'Admin access',
      'Salesforce objects with multiple fields configured',
    ]),
    crmNotes: 'Salesforce: Admin selects from available Salesforce fields based on the connected org schema.',
    pageRef: 'p99-101',
    displayOrder: 5,
  },
  {
    categorySlug: 'administration',
    title: 'Copilot for Sales for M365 Apps Configuration',
    userStory: 'As an admin, I want to configure Copilot for Sales deployment within M365 apps so I can control where it appears.',
    persona: 'Admin',
    testSteps: JSON.stringify([
      'Navigate to M365 Admin Center > Org Settings',
      'Find the Copilot for Sales configuration',
      'Configure which M365 apps show the Copilot for Sales entry point',
      'Save and verify the notification banner appears in configured apps',
      'Verify Copilot for Sales is not visible in non-configured apps',
    ]),
    prerequisites: JSON.stringify([
      'M365 Admin Center access',
      'Copilot for Sales license deployed to the tenant',
    ]),
    crmNotes: null,
    pageRef: 'p102',
    displayOrder: 6,
  },
  {
    categorySlug: 'administration',
    title: 'Role-Based Access to Settings Sections',
    userStory: 'As an admin, I want settings sections to be accessible based on admin role (Tenant vs Environment) so permissions are properly scoped.',
    persona: 'Admin',
    testSteps: JSON.stringify([
      'Sign in as a Tenant Admin and note all visible settings sections',
      'Sign in as an Environment Admin and note visible sections',
      'Sign in as a non-admin seller and verify settings are not accessible',
      'Compare Tenant Admin view vs Environment Admin view',
      'Verify Tenant Admins can access all sections',
      'Verify Environment Admins can only access environment-scoped settings',
    ]),
    prerequisites: JSON.stringify([
      'Users with Tenant Admin, Environment Admin, and Seller roles',
    ]),
    crmNotes: null,
    pageRef: 'p103-105',
    displayOrder: 7,
  },
  {
    categorySlug: 'administration',
    title: 'Salesforce Notes Object Configuration',
    userStory: 'As an admin, I want to configure saving email summaries to the Salesforce Notes object so sellers can leverage standard Notes.',
    persona: 'Admin',
    testSteps: JSON.stringify([
      'Navigate to Admin Settings > CRM Integration',
      'Enable the "Save to Salesforce Notes" option',
      'Configure which summaries auto-save to Notes',
      'Test by saving an email summary as a seller',
      'Verify the summary appears as a Note on the Salesforce record',
      'Check note formatting and content completeness',
    ]),
    prerequisites: JSON.stringify([
      'Salesforce org with Notes object enabled',
      'Admin access to Copilot for Sales settings',
    ]),
    crmNotes: 'Salesforce: Uses the ContentNote object. Requires Notes to be enabled in Salesforce org settings.',
    pageRef: 'p106',
    displayOrder: 8,
  },
  {
    categorySlug: 'administration',
    title: 'Enhanced Teams App - Admin Deployment',
    userStory: 'As an admin, I want to deploy the Copilot for Sales Teams app to my organization so all sellers have access.',
    persona: 'Admin',
    testSteps: JSON.stringify([
      'Navigate to Teams Admin Center > Manage Apps',
      'Find and select the Copilot for Sales app',
      'Configure app deployment policies for target users/groups',
      'Deploy the app to the organization',
      'Verify sellers see the app in their Teams app bar',
      'Confirm the app functions correctly after deployment',
    ]),
    prerequisites: JSON.stringify([
      'Teams Admin Center access',
      'Copilot for Sales license',
    ]),
    crmNotes: null,
    pageRef: 'p107',
    displayOrder: 9,
  },
  {
    categorySlug: 'administration',
    title: 'Collaboration Spaces Settings',
    userStory: 'As an admin, I want to configure Collaboration Spaces settings so I control how sellers create and use team spaces.',
    persona: 'Admin',
    testSteps: JSON.stringify([
      'Navigate to Admin Settings > Collaboration Spaces',
      'Enable or disable the Collaboration Spaces feature',
      'Configure which CRM objects support collaboration spaces',
      'Set permissions for who can create spaces',
      'Save and verify sellers see the updated options',
    ]),
    prerequisites: JSON.stringify([
      'Admin access',
      'Microsoft Teams available in the environment',
    ]),
    crmNotes: null,
    pageRef: 'p108',
    displayOrder: 10,
  },
  {
    categorySlug: 'administration',
    title: 'Copilot Studio - Create Actions',
    userStory: 'As an admin, I want to create custom actions in Copilot Studio for Copilot for Sales so I can extend its capabilities.',
    persona: 'Admin',
    testSteps: JSON.stringify([
      'Open Copilot Studio and select the Copilot for Sales extension',
      'Create a new custom action',
      'Define triggers, conditions, and CRM data interactions',
      'Test the action in the Copilot Studio test environment',
      'Publish the action to production',
      'Verify the action is available to sellers in Copilot for Sales',
    ]),
    prerequisites: JSON.stringify([
      'Copilot Studio license and access',
      'Copilot for Sales extension configured',
    ]),
    crmNotes: null,
    pageRef: 'p109',
    displayOrder: 11,
  },
  {
    categorySlug: 'administration',
    title: 'Copilot Studio - Enable Plugins',
    userStory: 'As an admin, I want to enable or disable Copilot Studio plugins so I control which extensions are available.',
    persona: 'Admin',
    testSteps: JSON.stringify([
      'Open Admin Settings > Copilot Studio Plugins',
      'View the list of available plugins',
      'Enable a disabled plugin and verify it becomes available to sellers',
      'Disable an enabled plugin and verify it is no longer accessible',
      'Verify plugin state changes take effect within a reasonable time',
    ]),
    prerequisites: JSON.stringify([
      'Copilot Studio configured with available plugins',
      'Admin access',
    ]),
    crmNotes: null,
    pageRef: 'p110',
    displayOrder: 12,
  },
  {
    categorySlug: 'administration',
    title: 'Enable Sharing Records in Emails',
    userStory: 'As an admin, I want to enable the "share records in emails" feature so sellers can embed CRM records in their communications.',
    persona: 'Admin',
    testSteps: JSON.stringify([
      'Navigate to Admin Settings > Email Features',
      'Find the "Sharing Records in Emails" toggle',
      'Enable the feature and save',
      'Sign in as a seller and compose a new email',
      'Verify the "/" command to insert CRM records is available',
      'Disable the feature and verify it is no longer available to sellers',
    ]),
    prerequisites: JSON.stringify([
      'Admin access to Copilot for Sales settings',
    ]),
    crmNotes: null,
    pageRef: 'p112',
    displayOrder: 13,
  },
  {
    categorySlug: 'administration',
    title: 'Connect Agents to Data Source (Salesforce)',
    userStory: 'As an admin, I want to connect Copilot for Sales agents to my Salesforce instance so they can access CRM data.',
    persona: 'Admin',
    testSteps: JSON.stringify([
      'Navigate to Admin Settings > Data Sources',
      'Select "Add Salesforce Connection"',
      'Enter Salesforce org details and authenticate',
      'Verify the connection is established successfully',
      'Test data retrieval from Salesforce through the connection',
      'Verify agents can access Salesforce data after connection',
    ]),
    prerequisites: JSON.stringify([
      'Salesforce org with API access enabled',
      'Admin credentials for both Copilot for Sales and Salesforce',
    ]),
    crmNotes: 'Salesforce: Uses the Salesforce connector. Requires API permissions and Connected App configuration.',
    pageRef: 'p113',
    displayOrder: 14,
  },
  {
    categorySlug: 'administration',
    title: 'Configure Auto Record Meetings',
    userStory: 'As an admin, I want to configure automatic meeting recording so CRM-relevant meetings are always captured.',
    persona: 'Admin',
    testSteps: JSON.stringify([
      'Navigate to Admin Settings > Meeting Settings',
      'Enable "Auto Record Meetings" for CRM-related meetings',
      'Configure criteria for which meetings to auto-record',
      'Save the configuration',
      'Schedule a meeting with an external CRM contact and verify auto-recording starts',
      'Verify internal-only meetings are not auto-recorded (if configured)',
    ]),
    prerequisites: JSON.stringify([
      'Teams meeting recording permissions',
      'Admin access to Copilot for Sales settings',
    ]),
    crmNotes: null,
    pageRef: 'p114',
    displayOrder: 15,
  },
  {
    categorySlug: 'administration',
    title: 'Configure Save AI Meeting Notes',
    userStory: 'As an admin, I want to configure how AI meeting notes are saved to CRM so the right data reaches the right records.',
    persona: 'Admin',
    testSteps: JSON.stringify([
      'Navigate to Admin Settings > Meeting Notes Configuration',
      'Configure auto-save settings (enabled/disabled, target object)',
      'Select which CRM fields to populate from meeting notes',
      'Configure which meeting types trigger note saves',
      'Save and test with a new meeting',
      'Verify notes are saved to Salesforce according to configuration',
    ]),
    prerequisites: JSON.stringify([
      'Admin access',
      'AI meeting notes feature available',
    ]),
    crmNotes: 'Salesforce: Notes can be saved to ContentNote or custom objects depending on configuration.',
    pageRef: 'p115-116',
    displayOrder: 16,
  },
  {
    categorySlug: 'administration',
    title: 'Manage Access for Features & Agents',
    userStory: 'As an admin, I want to manage which users can access specific features and agents so I maintain proper governance.',
    persona: 'Admin',
    testSteps: JSON.stringify([
      'Navigate to Admin Settings > Access Management',
      'Select a feature or agent to manage access for',
      'Assign access to specific user groups or security groups',
      'Remove access from a group and verify users lose visibility',
      'Test feature visibility with users in different access groups',
      'Verify changes take effect within the expected timeframe',
    ]),
    prerequisites: JSON.stringify([
      'Admin access',
      'Microsoft 365 security groups configured',
    ]),
    crmNotes: null,
    pageRef: 'p118',
    displayOrder: 17,
  },
  {
    categorySlug: 'administration',
    title: 'Sales Agent Configuration',
    userStory: 'As an admin, I want to configure Sales Agent settings including CRM connection, glossary, and custom instructions.',
    persona: 'Admin',
    testSteps: JSON.stringify([
      'Navigate to Admin Settings > Sales Agent',
      'Configure the CRM connection for the agent',
      'Set up the Sales Agent glossary with company-specific terms',
      'Configure which CRM fields the Sales Chat can access',
      'Add custom AI instructions for the agent',
      'Test the Sales Agent as a seller and verify it uses the configuration',
    ]),
    prerequisites: JSON.stringify([
      'Sales Agent feature available',
      'Admin access',
      'Salesforce connection established',
    ]),
    crmNotes: 'Salesforce: Agent accesses Salesforce data through the configured connector. Custom fields must be explicitly enabled.',
    pageRef: 'p119-123',
    displayOrder: 18,
  },
  {
    categorySlug: 'administration',
    title: 'Manage Showing Sentiment Analysis',
    userStory: 'As an admin, I want to enable or disable sentiment analysis display so I can control whether sellers see sentiment indicators.',
    persona: 'Admin',
    testSteps: JSON.stringify([
      'Navigate to Admin Settings > AI Features',
      'Find the "Show Sentiment Analysis" toggle',
      'Enable it and verify sellers see sentiment indicators on communications',
      'Disable it and verify sentiment indicators are hidden',
      'Verify the toggle only affects display, not underlying data processing',
    ]),
    prerequisites: JSON.stringify([
      'Admin access to Copilot for Sales settings',
    ]),
    crmNotes: null,
    pageRef: 'p117',
    displayOrder: 19,
  },
];

// ──────────────────────────────────────────────
// MONITORING  (~3 test cases)
// ──────────────────────────────────────────────

const monitoring: SeedTestCase[] = [
  {
    categorySlug: 'monitoring',
    title: 'Viva Insights - Analyst Workbench',
    userStory: 'As a manager, I want to analyze Copilot for Sales usage through Viva Insights so I can understand adoption and impact.',
    persona: 'Manager / Analyst',
    testSteps: JSON.stringify([
      'Open Viva Insights Analyst Workbench',
      'Navigate to the Copilot for Sales analytics section',
      'Verify adoption metrics are displayed (active users, feature usage)',
      'Apply filters (date range, department, role)',
      'Export a report of Copilot usage data',
      'Verify data accuracy by cross-referencing with known user activity',
    ]),
    prerequisites: JSON.stringify([
      'Viva Insights license with Analyst Workbench access',
      'Copilot for Sales deployed with active users',
      'Sufficient usage data accumulated',
    ]),
    crmNotes: null,
    pageRef: 'p125',
    displayOrder: 1,
  },
  {
    categorySlug: 'monitoring',
    title: 'CxO Dashboard',
    userStory: 'As an executive, I want a high-level dashboard showing Copilot for Sales impact so I can measure ROI.',
    persona: 'CxO / Executive',
    testSteps: JSON.stringify([
      'Access the CxO Dashboard for Copilot for Sales',
      'Verify high-level metrics: adoption rate, time saved, CRM update frequency',
      'Check that trend lines show adoption over time',
      'Verify department-level breakdowns are available',
      'Compare metrics against baseline (pre-Copilot data if available)',
      'Export or share the dashboard with stakeholders',
    ]),
    prerequisites: JSON.stringify([
      'CxO Dashboard access configured',
      'Copilot for Sales deployed for at least 30 days with active usage',
    ]),
    crmNotes: null,
    pageRef: 'p126',
    displayOrder: 2,
  },
  {
    categorySlug: 'monitoring',
    title: 'Copilot for Sales Adoption Metrics',
    userStory: 'As a project lead, I want to track Copilot for Sales adoption metrics so I can identify underutilized features and drive training.',
    persona: 'Project Lead',
    testSteps: JSON.stringify([
      'Access the adoption metrics dashboard',
      'Verify per-feature usage metrics (email summaries, CRM saves, meeting recaps)',
      'Check user-level engagement data',
      'Identify features with low adoption rates',
      'Compare adoption across different teams or departments',
      'Set up alerts for adoption threshold changes',
    ]),
    prerequisites: JSON.stringify([
      'Monitoring/analytics access configured',
      'Copilot for Sales with multiple active features',
      'Multiple user groups using the product',
    ]),
    crmNotes: null,
    pageRef: 'p125-127',
    displayOrder: 3,
  },
];

// ──────────────────────────────────────────────
// COMBINED EXPORT
// ──────────────────────────────────────────────

export const testCases: SeedTestCase[] = [
  ...productivity,
  ...interactions,
  ...flowOfWork,
  ...administration,
  ...monitoring,
];
